cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: 
      secret-key: 
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/651923658728/Notification-queue

server:
  port: 8083
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/Notifications
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

