spring:
  datasource:
    url: jdbc:mysql://cz72nhjogmiv.us-east-2.rds.amazonaws.com:3306/database-1-instance-1
    username: rootroot
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update


cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: 
      secret-key: 
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/651923658728/Notification-queue










